#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1485909913                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
#presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Simple and Powerful Waymarking. Experience a whole new way to play the game of Waymarking!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name                                 : Zed Said Studio LLC                              
your_link                                 : http://www.zedsaid.com                       
your_city                                 : the Pacific Northwest                             
email_address                             : support@waymarkly.com
facebook_username                         : groups/waymarkly                                 
twitter_username                          : waymarkly



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Authorized Developer
    description                           : Official partner app of waymarking.com and Geocaching HQ.
    fontawesome_icon_name                 : handshake
    
  - title                                 : Search the Globe
    description                           : Search for over 900,000 Waymarks across the globe!
    fontawesome_icon_name                 : search

  - title                                 : Log a Visit
    description                           : Quickly log your visit right from the app.
    fontawesome_icon_name                 : pencil-alt

  - title                                 : Search Filtering
    description                           : Hide your visits and hides or filter by categories.
    fontawesome_icon_name                 : filter

  - title                                 : Save Offline
    description                           : Add Waymarks to offline lists that include powerful filtering.
    fontawesome_icon_name                 : times
  
  - title                                 : Premium Offline Maps
    description                           : Beautiful OSM source offline maps of the globe.
    fontawesome_icon_name                 : map

  - title                                 : Highlight
    description                           : Mark Waymarks with various colors for reference.
    fontawesome_icon_name                 : highlighter

  - title                                 : Export GPX
    description                           : Save a GPX for use in Cachly or other apps.
    fontawesome_icon_name                 : share

  - title                                 : Text Templates
    description                           : Custom log text templates for quick usage.
    fontawesome_icon_name                 : file-alt

  - title                                 : Proximity Alert
    description                           : Get alerted when you come close to a Waymark.
    fontawesome_icon_name                 : target



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#e84c3d"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#e84c3d"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
